In [3]:
import pandas

df = pandas.read_csv('score.sc', sep='\s+', header=1)
df.sort_values('total_score').head()

,SCORE:,total_score,atom_pair_constraint,cart_bonded,dslf_fa13,fa_atr,fa_dun_dev,fa_dun_rot,fa_dun_semi,fa_elec,...,hxl_tors,lk_ball,lk_ball_bridge,lk_ball_bridge_uncpl,lk_ball_iso,omega,p_aa_pp,rama_prepro,ref,description
64,SCORE:,9073.354,9307.795,293.577,0.0,-2507.368,41.824,157.677,449.088,-214.189,...,55.462,169.678,-6.825,-39.651,-210.727,45.583,-123.605,-24.459,165.468,S_0065
61,SCORE:,9147.599,9307.310,390.228,0.0,-2564.796,42.507,170.778,452.243,-239.790,...,52.646,171.390,-6.583,-34.547,-216.095,59.029,-135.627,-2.319,165.468,S_0062
84,SCORE:,9153.434,9315.571,367.606,0.0,-2529.265,41.718,176.805,447.357,-228.501,...,55.000,173.909,-7.065,-36.314,-217.802,59.637,-144.387,-12.669,165.468,S_0085
50,SCORE:,9156.205,9317.043,347.379,0.0,-2514.179,44.710,176.887,451.877,-229.309,...,56.225,166.203,-6.720,-37.363,-207.282,62.370,-121.767,-8.646,165.468,S_0051
49,SCORE:,9158.013,9313.074,351.005,0.0,-2547.063,44.364,174.152,452.983,-235.409,...,52.422,180.367,-6.807,-35.531,-218.285,54.543,-138.097,0.454,165.468,S_0050